services:
  techhive:
    build: .
    image: techhive:latest
    env_file:
      - .env
    networks:
      - "traefik.enable=true"
      - "traefik.http.routers.techhive.rule=PathPrefix(`/techhive`)"
      - "traefik.http.routers.techhive.entrypoints=web"
      - "traefik.http.services.techhive.loadbalancer.server.post=3000"
      - "traefik.http.middlewares.techhive-string.stripprefix.prefixes=/techhive"
      - "traefik.http.routers.techhive.middlewares=techhive-strip"

networks:
  web: {}
