services:
  techhive:
    build: .
    image: techhive:latest
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.techhive.rule=PathPrefix(`/techhive`)"
      - "traefik.http.routers.techhive.entrypoints=web"
      - "traefik.http.services.techhive.loadbalancer.server.port=3000"
    networks:
      - web

networks:
  web:
    external: true
